apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: postgres
  annotations:
    metallb.universe.tf/address-pool: postgres-pool
spec:
  type: LoadBalancer
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
